name: Start Site
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Manual Start Site'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: https://github.com/xcratch/scratch-gui
          ref: xcratch
          path: ./scratch-gui
      - run: npm install --save --legacy-peer-deps
        working-directory: ./scratch-gui
      - uses: actions/checkout@v2
        with:
          repository: https://github.com/sakai-labo/mbit-more-v2-with-radio
          ref: master
          path: ./mbit-more-v2-with-radio
      - uses: actions/checkout@v2
        with:
          repository: https://github.com/sakai-labo/microbitMorev2-with-Radio.github.io
          ref: main
          path: ./microbitMorev2-with-Radio.github.io
      - run: node ./scripts/replace-logo.js ../scratch-gui
        working-directory: ./microbitMorev2-with-Radio.github.io
      - run: node ./scripts/original-assets.js ../scratch-gui
        working-directory: ./microbitMorev2-with-Radio.github.io
      - run: npm run build
        working-directory: ./scratch-gui
      - run: cp ./xcratch.github.io/editor/favicon.ico ./scratch-gui/build/static/favicon.ico
      - run: mv -T ./xcratch.github.io/public ./public
      - run: mv -T ./scratch-gui/build ./public/editor
      - run: mv -T ./mbit-more-v2-with-radio ./public/dist
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: .
          keep_files: true
